version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo

commands:
  setup:
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            sudo pip install poetry
            poetry install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

jobs:
  flake8:
    executor: my-executor
    steps:
      - setup
      - run: poetry run tox -e flake8

  mypy:
    executor: my-executor
    steps:
      - setup
      - run: poetry run tox -e mypy

  readme:
    executor: my-executor
    steps:
      - setup
      - run: poetry run tox -e readme

  unittest:
    executor: my-executor
    steps:
      - setup
      - run: poetry run tox -e py37

workflows:
  version: 2
  check_and_test:
    jobs:
      - flake8
      - mypy
      - readme
      - unittest
